import http from "k6/http";
import { check, sleep } from "k6";

const social_texts = [
  "pq vc n vem",
  "vlw mano, dps a gente se fala",
  "tbm achei isso mt loko kkk",
  "vc viu oq rolou hj?",
  "to mt cansado msm",
  "hahaha n acredito nisso",
  "q dia loko q passei hj",
  "eu n sei oq fazer :/",
  "vc vai na festa amanha?",
  "mt bom ver vc hj",
  "n to afim de sair hj",
  "to com fome, alguem tem ideia do q comer?",
  "kkk morri de rir",
  "vc ja terminou o trabalho?",
  "n acredito q ele falou isso",
  "to com mt sono",
  "pq ele fez isso comigo?",
  "hj ta mt calor",
  "vc vai na escola amanha?",
  "to mt feliz hj",
  "vc n vai acreditar oq aconteceu",
  "kkkkkkk mt bom",
  "hj ta chuvoso :(",
  "pq vc me ignorou?",
  "vlw msm pela ajuda",
  "to quase chegando em casa",
  "to triste hj",
  "q horas vc vai chegar?",
  "vc viu o video q mandei?",
  "ta td bem?",
  "n acredito q perdi o jogo",
  "to mt animado hj",
  "vc vai viajar nas ferias?",
  "to sem grana :(",
  "vc ja almoçou?",
  "to mt ocupado hj",
  "hahahaha q engraçado",
  "vc ta dormindo?",
  "to n acreditando",
  "hj foi mt corrido",
  "q absurdo isso kkk",
  "vc vai pro rolê hj?",
  "to mt feliz por vc",
  "n sei oq dizer",
  "vc viu a noticia?",
  "to mt gripado",
  "q chato isso",
  "kkk q isso mano",
  "vc n vai acreditar oq eu vi",
  "to quase desistindo",
  "hj to de boa",
  "vc me ajuda nisso?",
  "to mt nervoso",
  "kkk mt bom msm",
  "vc sabe oq aconteceu?",
  "to mt triste hj",
  "hj to animado",
  "vc ta bem?",
  "to mt cansado",
  "pq n me chamou?",
  "vlw msm",
  "to indo pra escola",
  "hj foi mt legal",
  "vc n vai querer acreditar",
  "to mt ocupado",
  "kkkk q isso",
  "vc viu oq rolou?",
  "to mt feliz hj",
  "hj ta mt frio",
  "vc ta online?",
  "to mt empolgado",
  "n acredito q vc fez isso",
  "hj to de saco cheio",
  "vc vai pro cinema?",
  "to mt triste ainda",
  "kkk q engraçado",
  "vc me entendeu?",
  "to quase chegando",
  "hj foi mt cansativo",
  "vc vai dormir cedo?",
  "to mt animado hj",
  "vc ta aonde?",
  "to mt estressado",
  "kkkk q da hora",
  "vc viu oq eu postei?",
  "to mt feliz hj",
  "hj ta mt calor",
  "vc vai no show?",
  "to mt preocupado",
  "n acredito q aconteceu isso",
  "hj ta chuvoso",
  "vc ta ocupado?",
  "to mt contente hj",
  "vc ta online ainda?",
  "to mt cansado hj",
  "kkk n acredito nisso",
  "vc viu a foto?",
  "to mt animado pra festa",
  "hj to de boa",
  "vc ta dormindo agora?",
  "to mt nervoso hj",
  "kkk q engraçado isso",
  "vc ta pronto?",
  "to mt triste ainda hj",
  "hj foi mt legal",
  "vc me chama depois?",
  // Gerando mais frases com variações e combinações
  "vc n vem hj?",
  "to de boa aki",
  "q dia louco kkk",
  "pq ta assim?",
  "vc ja comeu?",
  "to sem tempo hj",
  "kkk mt engraçado",
  "vc vai viajar?",
  "to mt feliz hj :D",
  "hj to cansado",
  "vc viu oq postei?",
  "to triste ainda :(",
  "q isso mano kkk",
  "hj ta friozinho",
  "vc ta ocupado?",
  "to mt animado pra festa",
  "vc vai na balada?",
  "hj foi mt corrido",
  "n acredito q aconteceu isso",
  "vc ta online?",
  "to quase indo pra casa",
  "kkk q loco",
  "vc vai no cinema?",
  "to mt gripado",
  "hj to de boa",
  "vc viu o video?",
  "to mt feliz hj",
  "pq n me chamou?",
  "vc vai viajar nas ferias?",
  "to mt cansado",
  "kkk mt bom msm",
  "vc ta pronto?",
  "to mt animado",
  "hj ta chuvoso",
  "vc me ajuda?",
  "to mt triste",
  "n acredito q vc fez isso",
  "hj foi mt legal",
  "vc ja terminou o trabalho?",
  "to mt preocupado",
  "vc viu a noticia?",
  "to quase chegando",
  "hj ta calor",
  "vc vai pro rolê?",
  "to mt nervoso",
  "kkkk q da hora",
  "vc ta aonde?",
  "to mt empolgado",
  "hj to de saco cheio",
  "vc me entendeu?",
  "to mt contente",
  "kkk q engraçado",
  "vc ta dormindo?",
  "to mt animado hj",
  "vc viu a foto?",
  "to mt cansado hj",
  "hj foi mt corrido",
  "vc me chama depois?",
  "to mt feliz",
  "vc vai no show?",
  "kkk q isso",
  "vc ta bem?",
  "to mt triste hj",
  "hj ta frio",
  "vc ja almoçou?",
  "to quase desistindo",
  "vc ta online ainda?",
  "to mt gripado hj",
  "kkk n acredito nisso",
  "vc viu oq eu postei?",
  "to mt feliz :D",
  "hj ta mt calor",
  "vc vai dormir cedo?",
  "to mt estressado",
  "kkk q engraçado isso",
  "vc ta pronto?",
  "to mt animado ainda",
  "hj foi mt legal",
  "vc me ajuda nisso?",
  "to mt nervoso hj",
  "vc n vai acreditar oq aconteceu",
  "to quase indo pra escola",
  "vc ja terminou?",
  "to mt cansado",
  "hj to de boa",
  "kkk mt bom",
  "vc ta aonde agora?",
  "to mt contente hj",
  "hj ta chuvoso",
  "vc vai no cinema?",
  "to mt gripado",
  "vc viu o video q mandei?",
  "to mt feliz hj :D",
  "kkk q loco",
  "vc ta online?",
  "to quase chegando em casa",
  "hj foi mt corrido",
  "vc me chama depois?",
  "to mt animado",
  "vc vai na festa?",
  "hj ta friozinho",
  "vc ta ocupado?",
  "to mt triste",
  "kkk mt bom msm",
  "vc ta pronto?",
  "to mt empolgado",
  "hj foi mt legal",
  "vc me ajuda?",
  "to mt nervoso",
  "vc n acredita nisso?",
  "to mt cansado hj",
  "hj to de boa",
  "vc viu a noticia?",
  "to mt feliz :D",
  "kkk q engraçado",
  "vc ta online ainda?",
  "to quase indo pra escola",
  "hj ta mt calor",
  "vc vai pro rolê?",
  "to mt gripado",
  "vc viu a foto?",
  "to mt animado ainda",
  "hj foi mt corrido",
  "vc me chama depois?",
  "to mt contente",
  "vc ta aonde?",
  "kkk q da hora",
  "vc viu oq aconteceu?",
  "to mt feliz hj",
  "hj ta frio",
  "vc ta pronto?",
  "to mt nervoso hj",
  "kkk q loco",
  "vc ta ocupado?",
  "to mt animado :D",
  "hj to de boa",
  "vc vai no show?",
  "to mt triste",
  "kkk mt bom",
  "vc ta online?",
  "to mt empolgado",
  "hj foi mt legal",
  "vc me ajuda nisso?",
  "to quase desistindo",
  "hj ta mt calor",
  "vc vai dormir cedo?",
  "to mt cansado",
  "kkk q engraçado",
  "vc ta aonde?",
  "to mt animado hj",
  "hj foi mt corrido",
  "vc me chama depois?",
  "to mt contente",
  "vc viu o video?",
  "kkk mt bom msm",
  "vc ta pronto?",
  "to mt nervoso",
  "hj ta frio",
  "vc vai na festa?",
  "to mt gripado",
  "vc ta ocupado?",
];

export let options = {
  vus: 10,
  duration: "30s",
};

export default function () {
  const i = __ITER % social_texts.length;
  const payload = JSON.stringify({ msg: social_texts[i] });

  const params = {
    headers: { "Content-Type": "application/json" },
  };

  const res = http.post("http://127.0.0.1:8000/api/normalise", payload, params);

  check(res, {
    "status is 200": (r) => r.status === 200,
    "result exists": (r) => JSON.parse(r.body).result !== undefined,
  });
}
