from fastapi.testclient import TestClient
from run import app

client = TestClient(app)

social_texts = [
    "pq vc n vem",
    "vlw mano, dps a gente se fala",
    "tbm achei isso mt loko kkk",
    "vc viu oq rolou hj?",
    "to mt cansado msm",
    "hahaha n acredito nisso",
    "q dia loko q passei hj",
    "eu n sei oq fazer :/",
    "vc vai na festa amanha?",
    "mt bom ver vc hj",
    "n to afim de sair hj",
    "to com fome, alguem tem ideia do q comer?",
    "kkk morri de rir",
    "vc ja terminou o trabalho?",
    "n acredito q ele falou isso",
    "to com mt sono",
    "pq ele fez isso comigo?",
    "hj ta mt calor",
    "vc vai na escola amanha?",
    "to mt feliz hj",
    "vc n vai acreditar oq aconteceu",
    "kkkkkkk mt bom",
    "hj ta chuvoso :(",
    "pq vc me ignorou?",
    "vlw msm pela ajuda",
    "to quase chegando em casa",
    "to triste hj",
    "q horas vc vai chegar?",
    "vc viu o video q mandei?",
    "ta td bem?",
    "n acredito q perdi o jogo",
    "to mt animado hj",
    "vc vai viajar nas ferias?",
    "to sem grana :(",
    "vc ja almoçou?",
    "to mt ocupado hj",
    "hahahaha q engraçado",
    "vc ta dormindo?",
    "to n acreditando",
    "hj foi mt corrido",
    "q absurdo isso kkk",
    "vc vai pro rolê hj?",
    "to mt feliz por vc",
    "n sei oq dizer",
    "vc viu a noticia?",
    "to mt gripado",
    "q chato isso",
    "kkk q isso mano",
    "vc n vai acreditar oq eu vi",
    "to quase desistindo",
    "hj to de boa",
    "vc me ajuda nisso?",
    "to mt nervoso",
    "kkk mt bom msm",
    "vc sabe oq aconteceu?",
    "to mt triste hj",
    "hj to animado",
    "vc ta bem?",
    "to mt cansado",
    "pq n me chamou?",
    "vlw msm",
    "to indo pra escola",
    "hj foi mt legal",
    "vc n vai querer acreditar",
    "to mt ocupado",
    "kkkk q isso",
    "vc viu oq rolou?",
    "to mt feliz hj",
    "hj ta mt frio",
    "vc ta online?",
    "to mt empolgado",
    "n acredito q vc fez isso",
    "hj to de saco cheio",
    "vc vai pro cinema?",
    "to mt triste ainda",
    "kkk q engraçado",
    "vc me entendeu?",
    "to quase chegando",
    "hj foi mt cansativo",
    "vc vai dormir cedo?",
    "to mt animado hj",
    "vc ta aonde?",
    "to mt estressado",
    "kkkk q da hora",
    "vc viu oq eu postei?",
    "to mt feliz hj",
    "hj ta mt calor",
    "vc vai no show?",
    "to mt preocupado",
    "n acredito q aconteceu isso",
    "hj ta chuvoso",
    "vc ta ocupado?",
    "to mt contente hj",
    "vc ta online ainda?",
    "to mt cansado hj",
    "kkk n acredito nisso",
    "vc viu a foto?",
    "to mt animado pra festa",
    "hj to de boa",
    "vc ta dormindo agora?",
    "to mt nervoso hj",
    "kkk q engraçado isso",
    "vc ta pronto?",
    "to mt triste ainda hj",
    "hj foi mt legal",
    "vc me chama depois?",
]


def test_normalise_social_texts():
    for text in social_texts:
        response = client.post("/api/normalise", params={"msg": text})
        assert response.status_code == 200
        data = response.json()
        assert "result" in data
        assert isinstance(data["result"], str)
